include: package:pedantic/analysis_options.yaml
analyzer:
  exclude:
    - example/*.reflectable.dart
    - test/*.reflectable.dart
    - lib/**/*.g.dart
    - lib/generated
  strong-mode:
    implicit-casts: true
